### ISSUE TITLE
Where can I find Exbuddy's Documentation？

### ISSUE THREAD

**Issue by Andrycism** [MGramolini/ExBuddy#28]
I want to write some script by myself but I don't know how can I find API Documentation or other development information, neither Github nor Exbuddy' file. So where can I find it?

**Comment by Mattygs6** [comment]
ExBuddy itself really isn't an API and doesn't have much if any need for documentation.  This could happen at some point in the future, but since it is completely open source, everything you need to know to build a script is easily visible.  There are also quite a few example files in the project.
