### ISSUE TITLE
ExGuildLeve doesn't work properly on CN Client

### ISSUE THREAD

**Issue by Andrycism** [MGramolini/ExBuddy#59]
I'm trying to make a profile, which followed your official example, in order to turn in HW tradecraft leves automaticly. However I found that although it works properly on EN client, but stop at choosing window when using CN client.
![choosing window](https://user-images.githubusercontent.com/4706089/28916104-b0135850-7873-11e7-8618-83ecc6205a02.png)
And here is the profile:
`<While condition="ItemCount(12608) &gt; 6">
			<ExPickupGuildLeve leveIds="1084" leveType="Tradecraft" npcId="1011208" npcLocation="-55.9391, 15.14058, -42.68848" />
			<ExTurnInGuildLeve npcId="1011209" npcLocation="-55.9391, 15.14058, -42.68848" />
		</While>`
I checked the exbuddy files for twice to make sure it's the latest version. RBCN is also the latest version. I really want to know how to fix this issue to make it work on CN client, thank you.

**Comment by Mattygs6** [comment]
Does the CN client say "Tracecraft Leves." ?  the LeveType is a string to match on.  It was set up this way so that other language support was easier, but profiles couldn't be shared without changing this value.
